### ISSUE TITLE
Incorrect requirements.txt

### ISSUE THREAD

**Issue by srtnnm** [Shashankh001/spotify-music-downloader#1]
Please change requirements in requirements.txt to:
```
kivy
kivymd
termcolor
pyfiglet
youtube_search
pypresence
testresources
spotipy
```

**Comment by Shashankh001** [comment]
Thank you for correcting! If i may, may i ask if the app is good and functioning as expected?

**Comment by srtnnm** [comment]
No it's not, it's returning error

**Comment by DaZy4** [comment]
> **[Shashankh001](/Shashankh001) ** co

add automatically choosing directory 
here's code:
```
f'{os.getenv("HOME")}/Music'

**Comment by Shashankh001** [comment]
> No it's not, it's returning error

Could you specify the error?

**Comment by srtnnm** [comment]
> > No it's not, it's returning error
> 
> Could you specify the error?

no i can't bcuz it's couple of errors

**Comment by Shashankh001** [comment]
Run the code using the terminal and paste the error here.
