### ISSUE TITLE
Directory choosing

### ISSUE THREAD

**Issue by srtnnm** [Shashankh001/spotify-music-downloader#2]
Please make an automatic selection of the directory
here's code:
```
f'{os.getenv("HOME")}/Music'
```

**Comment by Shashankh001** [comment]
> Please make an automatic selection of the directory here's code:
> 
> ```
> f'{os.getenv("HOME")}/Music'
> ```

We will add that in the next update.

**Comment by Shashankh001** [comment]
A new update has been released. I have put that feature in it as well. Thank you.
